### PR TITLE
Jekyll Integrated version 

### PR DESCRIPTION
**Pull request by KamalNanda**

### CODE REVIEW

**Review by srijitcoder — CHANGES_REQUESTED** [review]
image

In many pages, there are a lot of white space towards the right hand side... Try to fix it. 
@KamalNanda

**Comment by KamalNanda** [comment]
This page only has this single event , that's why it looks empty

**Comment by KamalNanda** [comment]
Solved

**Review by KamalNanda — COMMENTED** [review]
the white space in the right problem is solved

**Review by srijitcoder — APPROVED** [review]

**Pull request merged**
